### ISSUE TITLE
Consider adding Session hijacking attack in check list

### ISSUE THREAD

**Issue by peter279k** [ismailtasdelen/php-security-check-list#1]
As title, we can consider adding the following list:

- https://www.owasp.org/index.php/Session_hijacking_attack

This is also a security issue to be checked/considered.

**Comment by ismailtasdelen** [comment]
Of course @peter279k 👍

**Comment by peter279k** [comment]
Do you reopen this issue?

I can create this PR if possible at my available time.

**Comment by peter279k** [comment]
@ismailtasdelen. Resolves issue #1 via PR #3.
